### ISSUE TITLE
Implicit Assign ApiKey

### ISSUE THREAD

**Issue by Emopusta** [RhymeRone/MyGPT#1]
I suggest you to remove your OpenAI Api Key from program.cs Line 15. take it into an env or appsettings file then get it from that file. Don't publish it to github, keep it hidden.

**Comment by RhymeRone** [comment]
> I suggest you to remove your OpenAI Api Key from program.cs Line 15. take it into an env or appsettings file then get it from that file. Don't publish it to github, keep it hidden.

thanks but its not working, just example
